import type { Marker } from '../data/mock'

export const projectFixture: Marker = {
  id: 'project-test',
  title: 'Тестовый проект',
  description: 'Описание проекта',
  category: 'projects',
  date: '2024-06-15',
  city: 'Москва',
  distance: '42 км',
  status: 75,
  images: [
    { url: 'https://example.com/project.jpg' },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Подготовить программу',
      description: 'Составить список докладчиков',
      coordinates: [37.6241, 55.7521],
      category: 'projects',
      date: '2024-05-01',
      city: 'Москва',
      status: 'completed',
      images: [],
    },
    {
      id: 'task-2',
      title: 'Найти спонсоров',
      description: 'Связаться с компаниями',
      coordinates: [37.6098, 55.7612],
      category: 'projects',
      date: '2024-05-15',
      city: 'Москва',
      status: 'completed',
      images: [],
    },
    {
      id: 'task-3',
      title: 'Аренда зала',
      description: 'Забронировать помещение',
      coordinates: [37.6322, 55.7488],
      category: 'projects',
      date: '2024-06-01',
      city: 'Москва',
      status: 50,
      images: [],
    },
    {
      id: 'task-4',
      title: 'Пригласить спикеров',
      description: 'Отправить приглашения',
      coordinates: [37.5987, 55.7549],
      category: 'projects',
      date: '2024-06-10',
      city: 'Москва',
      status: 75,
      images: [],
    },
    {
      id: 'task-5',
      title: 'Организация питания',
      description: 'Заказать кейтеринг',
      coordinates: [37.6179, 55.7693],
      category: 'projects',
      date: '2024-06-12',
      city: 'Москва',
      status: 30,
      images: [],
    },
  ],
}

export const markerFixtures: Marker[] = [projectFixture]

export const projectListFixtures: Marker[] = [
  projectFixture,
  {
    id: 'project-completed',
    title: 'Startup Summit',
    description: 'Митап стартапов в центре',
    category: 'projects',
    date: '2024-07-20',
    city: 'Москва',
    distance: '7 км',
    status: 'completed',
    images: [],
    tasks: [],
  },
  {
    id: 'project-active',
    title: 'AI Hackathon',
    description: 'Хакатон по искусственному интеллекту',
    category: 'projects',
    date: '2024-08-10',
    city: 'Москва',
    distance: '15 км',
    status: 50,
    images: [],
    tasks: [],
  },
  {
    id: 'project-vue',
    title: 'Vue.js Meetup',
    description: 'Встреча разработчиков Vue',
    category: 'projects',
    date: '2024-09-05',
    city: 'Москва',
    distance: '9 км',
    status: 30,
    images: [],
    tasks: [],
  },
  {
    id: 'project-devops',
    title: 'DevOps Conference',
    description: 'Конференция по DevOps практикам',
    category: 'projects',
    date: '2024-10-12',
    city: 'Москва',
    distance: '12 км',
    status: 'completed',
    images: [],
    tasks: [],
  },
]

export const travelFixture: Marker = {
  id: 'travel-test',
  title: 'Тестовое путешествие',
  description: '',
  coordinates: [37.6173, 55.7558],
  category: 'travel',
  date: '2026-04-11',
  city: 'Москва',
  distance: '12 км',
  images: [],
}
